'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HideBooksWithoutAnnotations() As Boolean
            Get
                Return CType(Me("HideBooksWithoutAnnotations"),Boolean)
            End Get
            Set
                Me("HideBooksWithoutAnnotations") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CreateSeparateFileForEachBook() As Boolean
            Get
                Return CType(Me("CreateSeparateFileForEachBook"),Boolean)
            End Get
            Set
                Me("CreateSeparateFileForEachBook") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property InsertBookInformation() As Boolean
            Get
                Return CType(Me("InsertBookInformation"),Boolean)
            End Get
            Set
                Me("InsertBookInformation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CreateInlineImages() As Boolean
            Get
                Return CType(Me("CreateInlineImages"),Boolean)
            End Get
            Set
                Me("CreateInlineImages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ExpandMarkedText() As Boolean
            Get
                Return CType(Me("ExpandMarkedText"),Boolean)
            End Get
            Set
                Me("ExpandMarkedText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property CharactersToExpandMarkedTextBy() As Integer
            Get
                Return CType(Me("CharactersToExpandMarkedTextBy"),Integer)
            End Get
            Set
                Me("CharactersToExpandMarkedTextBy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HighlightOriginalMark() As Boolean
            Get
                Return CType(Me("HighlightOriginalMark"),Boolean)
            End Get
            Set
                Me("HighlightOriginalMark") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("body { text-align: justify; }"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"table, tr, td, th { border-style: solid; border-wi"& _ 
            "dth: 1px; border-color: #055f9d; border-collapse: collapse; }"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"th { text-align: "& _ 
            "left; vertical-align: top; padding: 5px; }"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"td { text-align: justify; vertical-a"& _ 
            "lign: top; padding: 5px; }"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"p { text-align: justify;  margin: 0; text-indent: 1e"& _ 
            "m; }"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"span.AnnotationHighlight { background-color: yellow }")>  _
        Public Property HtmlExport_CSS() As String
            Get
                Return CType(Me("HtmlExport_CSS"),String)
            End Get
            Set
                Me("HtmlExport_CSS") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property HtmlExport_SaveLayer() As String
            Get
                Return CType(Me("HtmlExport_SaveLayer"), String)
            End Get
            Set
                Me("HtmlExport_SaveLayer") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[table width='100%']")>  _
        Public Property HtmlExport_BookHead() As String
            Get
                Return CType(Me("HtmlExport_BookHead"),String)
            End Get
            Set
                Me("HtmlExport_BookHead") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[tr bgcolor='#e0ffff'][th align='left' colspan='3'][font size='+1']%AUTHOR%[/font"& _ 
            "][br][font size='+2']%TITLE%[/font][br][font size='-1'][i]%FILE_NAME%[/i][/font]"& _ 
            "[/th][/tr]")>  _
        Public Property HtmlExport_BookInformation() As String
            Get
                Return CType(Me("HtmlExport_BookInformation"),String)
            End Get
            Set
                Me("HtmlExport_BookInformation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[tr bgcolor='#e0ffff'][th align='center']Page[/th][th align='center' width='50%']"& _ 
            "Marked Text[/th][th align='center' width='50%']Annotation[/th][/tr]")>  _
        Public Property HtmlExport_AnnotationsHead() As String
            Get
                Return CType(Me("HtmlExport_AnnotationsHead"),String)
            End Get
            Set
                Me("HtmlExport_AnnotationsHead") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[tr][td]%PAGE%[/td][td]%MARKED_TEXT%[/td][td]%ANNOTATION%[/td][/tr]")>  _
        Public Property HtmlExport_Annotation() As String
            Get
                Return CType(Me("HtmlExport_Annotation"),String)
            End Get
            Set
                Me("HtmlExport_Annotation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[span class=""AnnotationHighlight""]")>  _
        Public Property HtmlExport_AnnotationHighlightStart() As String
            Get
                Return CType(Me("HtmlExport_AnnotationHighlightStart"),String)
            End Get
            Set
                Me("HtmlExport_AnnotationHighlightStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[/span]")>  _
        Public Property HtmlExport_AnnotationHighlightEnd() As String
            Get
                Return CType(Me("HtmlExport_AnnotationHighlightEnd"),String)
            End Get
            Set
                Me("HtmlExport_AnnotationHighlightEnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HtmlExport_AnnotationsSeparator() As String
            Get
                Return CType(Me("HtmlExport_AnnotationsSeparator"),String)
            End Get
            Set
                Me("HtmlExport_AnnotationsSeparator") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("[tr][td colspan='3'][i]No annotations available[/i][/td][/tr]")>
        Public Property HtmlExport_AnnotationsNotAvailable() As String
            Get
                Return CType(Me("HtmlExport_AnnotationsNotAvailable"), String)
            End Get
            Set
                Me("HtmlExport_AnnotationsNotAvailable") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property HtmlExport_Script() As String
            Get
                Return CType(Me("HtmlExport_Script"), String)
            End Get
            Set
                Me("HtmlExport_Script") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("[/table]\n[br][br]")>
        Public Property HtmlExport_BookTail() As String
            Get
                Return CType(Me("HtmlExport_BookTail"), String)
            End Get
            Set
                Me("HtmlExport_BookTail") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PageNumberDecimalPlaces() As Integer
            Get
                Return CType(Me("PageNumberDecimalPlaces"),Integer)
            End Get
            Set
                Me("PageNumberDecimalPlaces") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ToxAnnotationsExporter.My.MySettings
            Get
                Return Global.ToxAnnotationsExporter.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
